package Model;
// Generated 14/03/2020 09:49:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cdr generated by hbm2java
 */
public class Cdr  implements java.io.Serializable {


     private Integer id;
     private String subscriberId;
     private Date startTime;
     private Date finishTime;

    public Cdr() {
    }

	
    public Cdr(String subscriberId) {
        this.subscriberId = subscriberId;
    }
    public Cdr(String subscriberId, Date startTime, Date finishTime) {
       this.subscriberId = subscriberId;
       this.startTime = startTime;
       this.finishTime = finishTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(String subscriberId) {
        this.subscriberId = subscriberId;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }




}


